"""Additive Builder Home schema/parser surface for the builder-project-model roadmap."""

from .central_scheduler import (
    CentralSnapshot,
    ControllerSnapshot,
    HomeLockHandle,
    ProviderSimulation,
    WatchdogModel,
    acquire_home_lock,
    build_central_snapshot,
    discover_repo_controllers,
    held_home_lock,
    inspect_home_lock,
    snapshot_controller,
)
from .central_daemon import CentralDaemon, load_valid_snapshot, snapshot_digest
from .central_supervisor import CentralSupervisor, SupervisorDecision, acquire_supervisor_lock, daemon_identity_state
from .cutover import (
    FORWARD_STEPS,
    ROLLBACK_STEPS,
    CutoverError,
    CutoverOrchestrator,
    LaunchRequest,
    StepResult,
    SyntheticCutoverOperator,
    load_cutover_state,
    render_cutover_results,
    write_cutover_state,
)
from .attribution import AdmissionReceipt, AdmissionStore, Membership, receipt_for_work, resolve_admission_repo, should_enqueue_physical
from .authoring import AuthoringContext, emit_declaration_patch_handoff, load_authoring_context
from .draining import DrainLaunch, FederatedDrainer
from .dispatch_plan import DispatchPlanAction, build_dispatch_plan, render_dispatch_plan
from .editors import MutationPreview, apply_mutation_preview, plan_backlog_edit, plan_project_edit, plan_release_edit, plan_repo_register, plan_repo_unregister, render_mutation_preview
from .fair_share import FairShareCandidate, choose_candidate
from .governor import BuilderGovernor, GLOBAL_COOLDOWN_CLASSES, GovernorReservation, ReconcileAction, current_pid_start_ticks, governor_enabled
from .eligibility import (
    CooldownView,
    EligibilityEntry,
    LockStatus,
    ReplaySnapshot,
    inspect_scheduler_lock,
    legacy_replay_snapshot,
    load_repo_dispatch_config,
    normalize_provider,
    replay_observe_only,
    repo_runtime_paths,
)
from .home import BuilderHome, HomeProject, HomeRelease, lint_loaded_home, load_builder_home, load_optional_home, render_home_status, resolve_home_dir
from .importer import ImportPreview, apply_import_preview, preview_bia_import, render_import_preview
from .init import PlannedWrite, apply_plan, render_plan, scaffold_home
from .launcher_shim import command_digest, launcher_main, spawn_launcher, wait_for_slot_identity
from .live_command import live_command_builder
from .live_cutover import LiveCutoverOperator
from .live_runtime import CENTRAL_OWNER_PREFIX, activated_home_for_repo, live_activation, repo_id_for_root
from .lint import lint_home, lint_home_from_args
from .migration import MigrationVerification, ReleaseEquivalence, fingerprint_runtime_tree, render_migration_verification, verify_bia_import
from .ownership_guard import OwnershipGuardResult, evaluate_repo_ownership, refusal_message
from .readiness import ReadinessBlock, evaluate_cross_repo_dependencies
from .repo_controller import Candidate, ControllerStatus, LaunchLease, RepoController
from .session_store import SessionPaths, SessionStore, read_provider_state

__all__ = [
    "AdmissionReceipt",
    "AdmissionStore",
    "AuthoringContext",
    "BuilderHome",
    "CentralSnapshot",
    "CentralDaemon",
    "CentralSupervisor",
    "CutoverError",
    "CutoverOrchestrator",
    "Candidate",
    "ControllerSnapshot",
    "ControllerStatus",
    "CooldownView",
    "BuilderGovernor",
    "DispatchPlanAction",
    "DrainLaunch",
    "FairShareCandidate",
    "FederatedDrainer",
    "HomeProject",
    "HomeRelease",
    "HomeLockHandle",
    "ImportPreview",
    "EligibilityEntry",
    "GLOBAL_COOLDOWN_CLASSES",
    "GovernorReservation",
    "LaunchLease",
    "LaunchRequest",
    "LiveCutoverOperator",
    "CENTRAL_OWNER_PREFIX",
    "LockStatus",
    "MigrationVerification",
    "Membership",
    "MutationPreview",
    "OwnershipGuardResult",
    "PlannedWrite",
    "ProviderSimulation",
    "ReadinessBlock",
    "ReconcileAction",
    "RepoController",
    "ReplaySnapshot",
    "ReleaseEquivalence",
    "SessionPaths",
    "SessionStore",
    "StepResult",
    "SyntheticCutoverOperator",
    "SupervisorDecision",
    "WatchdogModel",
    "FORWARD_STEPS",
    "ROLLBACK_STEPS",
    "acquire_home_lock",
    "acquire_supervisor_lock",
    "apply_mutation_preview",
    "apply_import_preview",
    "apply_plan",
    "build_dispatch_plan",
    "build_central_snapshot",
    "emit_declaration_patch_handoff",
    "choose_candidate",
    "command_digest",
    "live_command_builder",
    "live_activation",
    "activated_home_for_repo",
    "repo_id_for_root",
    "current_pid_start_ticks",
    "discover_repo_controllers",
    "daemon_identity_state",
    "evaluate_cross_repo_dependencies",
    "evaluate_repo_ownership",
    "governor_enabled",
    "held_home_lock",
    "inspect_home_lock",
    "inspect_scheduler_lock",
    "launcher_main",
    "legacy_replay_snapshot",
    "lint_home",
    "lint_home_from_args",
    "lint_loaded_home",
    "load_authoring_context",
    "load_repo_dispatch_config",
    "load_builder_home",
    "load_cutover_state",
    "load_valid_snapshot",
    "load_optional_home",
    "normalize_provider",
    "plan_backlog_edit",
    "plan_project_edit",
    "plan_release_edit",
    "plan_repo_register",
    "plan_repo_unregister",
    "preview_bia_import",
    "read_provider_state",
    "receipt_for_work",
    "render_cutover_results",
    "render_migration_verification",
    "render_dispatch_plan",
    "replay_observe_only",
    "render_import_preview",
    "render_home_status",
    "render_mutation_preview",
    "render_plan",
    "repo_runtime_paths",
    "refusal_message",
    "resolve_admission_repo",
    "resolve_home_dir",
    "snapshot_controller",
    "snapshot_digest",
    "spawn_launcher",
    "scaffold_home",
    "should_enqueue_physical",
    "fingerprint_runtime_tree",
    "verify_bia_import",
    "wait_for_slot_identity",
    "write_cutover_state",
]
